name: Deploy Backend to Contabo VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # 1. Se positionner dans le dossier de prod
            cd /var/www/ttk-services
            
            # 2. Nettoyer et forcer l'alignement parfait avec GitHub
            git fetch --all
            git reset --hard origin/main
            git clean -df
            
            # 3. Lancer l'orchestration Docker Compose
            # Le flag --build recrée l'image de ton API et de tes workers
            docker compose up -d --build